# typed: false
# frozen_string_literal: true

# Generated by scripts/sync.sh — do not edit by hand.
class Ferrosa < Formula
  desc "Cassandra-compatible database engine with S3-backed storage"
  homepage "https://ferrosadb.com"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ferrosadb/ferrosa/releases/download/v0.19.1/ferrosa-v0.19.1-aarch64-apple-darwin.tar.gz"
      sha256 "eab638bc171739d2b90d2b5317137afa84a17e96671756aa446860a90b3d3f87"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ferrosadb/ferrosa/releases/download/v0.19.1/ferrosa-v0.19.1-aarch64-unknown-linux-musl.tar.gz"
      sha256 "5d0c2d939f15c23a0e6450f4c6108fd61eb2cb97878e483f1e08051377143596"
    end
    on_intel do
      url "https://github.com/ferrosadb/ferrosa/releases/download/v0.19.1/ferrosa-v0.19.1-x86_64-unknown-linux-musl.tar.gz"
      sha256 "d50cc0884355e263f51d6d4990931fe860f2a8a94a4e21aebaff89f7532b525c"
    end
  end

  def install
    bin.install "ferrosa"
    bin.install "ferrosa-ctl"
    (etc/"ferrosa").install "config/ferrosa.example.toml" if File.exist?("config/ferrosa.example.toml")
  end

  def caveats
    <<~EOS
      Ferrosa installed. A default config example is at:
        #{etc}/ferrosa/ferrosa.example.toml

      Start it manually:
        FERROSA_CONFIG="#{etc}/ferrosa/ferrosa.example.toml" ferrosa

      Brew tracks the stable channel. For nightlies use the curl installer:
        curl -fsSL https://ferrosadb.com/install.sh | bash -s -- --channel nightly
    EOS
  end

  test do
    # The main `ferrosa` binary boots the server on any args; `ferrosa-ctl`
    # is the CLI with a clean --version.
    assert_match version.to_s, shell_output("#{bin}/ferrosa-ctl --version")
  end
end
