# typed: false
# frozen_string_literal: true

# Generated by scripts/sync.sh — do not edit by hand.
class FerrosaMemory < Formula
  desc "Memory/knowledge-graph MCP server backed by Ferrosa"
  homepage "https://ferrosadb.com"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ferrosadb/ferrosa-memory/releases/download/v0.29.2/ferrosa-memory-v0.29.2-aarch64-apple-darwin.tar.gz"
      sha256 "4ba4f3db7b2339315c185a67d23fef13935aab344ea131e79a93830e3d724095"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ferrosadb/ferrosa-memory/releases/download/v0.29.2/ferrosa-memory-v0.29.2-aarch64-unknown-linux-musl.tar.gz"
      sha256 "6e341d43afefd5795a681d9bd82e63215996799180aeb9fbbb65443652994f47"
    end
    on_intel do
      url "https://github.com/ferrosadb/ferrosa-memory/releases/download/v0.29.2/ferrosa-memory-v0.29.2-x86_64-unknown-linux-musl.tar.gz"
      sha256 "b8d2785c5b555dafeb953622aea7940e884d2cc138af28034ff66a33d0f709aa"
    end
  end

  def install
    bin.install "ferrosa-memory-mcp"
    # Native setup CLI (`ferrosa-memory`) — ships in releases after v0.16.x.
    bin.install "ferrosa-memory" if File.exist?("ferrosa-memory")
    (etc/"ferrosa").install "config/ferrosa-memory.example.toml" if File.exist?("config/ferrosa-memory.example.toml")
  end

  def caveats
    <<~EOS
      ferrosa-memory-mcp installed. It connects to a running Ferrosa instance
      at localhost:9042 — install Ferrosa first:
        brew install ferrosadb/tap/ferrosa

      Register with Claude Code by adding to your MCP config:
        {
          "mcpServers": {
            "ferrosa-memory": {
              "command": "#{bin}/ferrosa-memory-mcp",
              "env": { "FERROSA_MEMORY_CONFIG": "#{etc}/ferrosa/ferrosa-memory.example.toml" }
            }
          }
        }
    EOS
  end

  test do
    # ferrosa-memory-mcp is a stdio MCP server with no --version flag; just
    # assert it landed. The native setup CLI has a clean --help when present.
    assert_predicate bin/"ferrosa-memory-mcp", :executable?
    assert_match "setup", shell_output("#{bin}/ferrosa-memory --help 2>&1") if (bin/"ferrosa-memory").exist?
  end
end
