# typed: false
# frozen_string_literal: true

# Generated by scripts/sync.sh — do not edit by hand.
class Ferrosa < Formula
  desc "Cassandra-compatible database engine with S3-backed storage"
  homepage "https://ferrosadb.com"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ferrosadb/ferrosa/releases/download/v0.19.0/ferrosa-v0.19.0-aarch64-apple-darwin.tar.gz"
      sha256 "117f098f8ed8d34ba7197ab5db136d334eb63102322bc4f27f0a9320b931a540"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ferrosadb/ferrosa/releases/download/v0.19.0/ferrosa-v0.19.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "106d053f76ca6ee9d758f34fe20440484deced1cd0ebb91bd299c1e933e1bca3"
    end
    on_intel do
      url "https://github.com/ferrosadb/ferrosa/releases/download/v0.19.0/ferrosa-v0.19.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "95efb275f08b372d70e5a340d65e0758ab593746c998bf0dec19a9f3e7fa175f"
    end
  end

  def install
    bin.install "ferrosa"
    bin.install "ferrosa-ctl"
    (etc/"ferrosa").install "config/ferrosa.example.toml" if File.exist?("config/ferrosa.example.toml")
  end

  def caveats
    <<~EOS
      Ferrosa installed. A default config example is at:
        #{etc}/ferrosa/ferrosa.example.toml

      Start it manually:
        FERROSA_CONFIG="#{etc}/ferrosa/ferrosa.example.toml" ferrosa

      Brew tracks the stable channel. For nightlies use the curl installer:
        curl -fsSL https://ferrosadb.com/install.sh | bash -s -- --channel nightly
    EOS
  end

  test do
    # The main `ferrosa` binary boots the server on any args; `ferrosa-ctl`
    # is the CLI with a clean --version.
    assert_match version.to_s, shell_output("#{bin}/ferrosa-ctl --version")
  end
end
