# typed: false
# frozen_string_literal: true

# Generated by scripts/sync.sh — do not edit by hand.
class FerrosaMemory < Formula
  desc "Memory/knowledge-graph MCP server backed by Ferrosa"
  homepage "https://ferrosadb.com"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ferrosadb/ferrosa-memory/releases/download/v0.21.0/ferrosa-memory-v0.21.0-aarch64-apple-darwin.tar.gz"
      sha256 "9cbf44546ea57bf7efb41ba8ce04165914f59357ce2b8b7cddfa846fa93b5288"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ferrosadb/ferrosa-memory/releases/download/v0.21.0/ferrosa-memory-v0.21.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "8495afa96f330306b18cd9569bc030686760d27e4ae89df00a33a838787b3b5f"
    end
    on_intel do
      url "https://github.com/ferrosadb/ferrosa-memory/releases/download/v0.21.0/ferrosa-memory-v0.21.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "6d6023a600f6d7351e4620f0e52e8bcc7c7be1989f1bf8c57528b2a4f18e1dbc"
    end
  end

  def install
    bin.install "ferrosa-memory-mcp"
    # Native setup CLI (`ferrosa-memory`) — ships in releases after v0.16.x.
    bin.install "ferrosa-memory" if File.exist?("ferrosa-memory")
    (etc/"ferrosa").install "config/ferrosa-memory.example.toml" if File.exist?("config/ferrosa-memory.example.toml")
  end

  def caveats
    <<~EOS
      ferrosa-memory-mcp installed. It connects to a running Ferrosa instance
      at localhost:9042 — install Ferrosa first:
        brew install ferrosadb/tap/ferrosa

      Register with Claude Code by adding to your MCP config:
        {
          "mcpServers": {
            "ferrosa-memory": {
              "command": "#{bin}/ferrosa-memory-mcp",
              "env": { "FERROSA_MEMORY_CONFIG": "#{etc}/ferrosa/ferrosa-memory.example.toml" }
            }
          }
        }
    EOS
  end

  test do
    # ferrosa-memory-mcp is a stdio MCP server with no --version flag; just
    # assert it landed. The native setup CLI has a clean --help when present.
    assert_predicate bin/"ferrosa-memory-mcp", :executable?
    assert_match "setup", shell_output("#{bin}/ferrosa-memory --help") if (bin/"ferrosa-memory").exist?
  end
end
