# typed: false
# frozen_string_literal: true

# Generated by scripts/sync.sh — do not edit by hand.
class FerrosaMemory < Formula
  desc "Memory/knowledge-graph MCP server backed by Ferrosa"
  homepage "https://ferrosadb.com"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ferrosadb/ferrosa-memory/releases/download/v0.22.0/ferrosa-memory-v0.22.0-aarch64-apple-darwin.tar.gz"
      sha256 "e03cf4ec92ad35fc6ec15cd98c450866fc27b92c43d447995b2694a004e337c7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ferrosadb/ferrosa-memory/releases/download/v0.22.0/ferrosa-memory-v0.22.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "0657325074885ec4b6f0811bb0f062b18a3b9c3440a77c33720e9abf8a2c6890"
    end
    on_intel do
      url "https://github.com/ferrosadb/ferrosa-memory/releases/download/v0.22.0/ferrosa-memory-v0.22.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "01671ead27000dc66499a1dc5b2621e93207a9dcc8c34bc4a4b364c7fd2fca5d"
    end
  end

  def install
    bin.install "ferrosa-memory-mcp"
    # Native setup CLI (`ferrosa-memory`) — ships in releases after v0.16.x.
    bin.install "ferrosa-memory" if File.exist?("ferrosa-memory")
    (etc/"ferrosa").install "config/ferrosa-memory.example.toml" if File.exist?("config/ferrosa-memory.example.toml")
  end

  def caveats
    <<~EOS
      ferrosa-memory-mcp installed. It connects to a running Ferrosa instance
      at localhost:9042 — install Ferrosa first:
        brew install ferrosadb/tap/ferrosa

      Register with Claude Code by adding to your MCP config:
        {
          "mcpServers": {
            "ferrosa-memory": {
              "command": "#{bin}/ferrosa-memory-mcp",
              "env": { "FERROSA_MEMORY_CONFIG": "#{etc}/ferrosa/ferrosa-memory.example.toml" }
            }
          }
        }
    EOS
  end

  test do
    # ferrosa-memory-mcp is a stdio MCP server with no --version flag; just
    # assert it landed. The native setup CLI has a clean --help when present.
    assert_predicate bin/"ferrosa-memory-mcp", :executable?
    assert_match "setup", shell_output("#{bin}/ferrosa-memory --help 2>&1") if (bin/"ferrosa-memory").exist?
  end
end
