# typed: false
# frozen_string_literal: true

# Generated by scripts/sync.sh — do not edit by hand.
class Ferrosa < Formula
  desc "Cassandra-compatible database engine with S3-backed storage"
  homepage "https://ferrosadb.com"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ferrosadb/ferrosa/releases/download/v0.21.1/ferrosa-v0.21.1-aarch64-apple-darwin.tar.gz"
      sha256 "946316d77a89a9fa9d002616eda548b929e66d6de26d77356651178fabef63ef"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ferrosadb/ferrosa/releases/download/v0.21.1/ferrosa-v0.21.1-aarch64-unknown-linux-musl.tar.gz"
      sha256 "36405cb1a50d6cf29b7d315ae494ae0cecf082dcf2b8255d26c69f520d0e9c9f"
    end
    on_intel do
      url "https://github.com/ferrosadb/ferrosa/releases/download/v0.21.1/ferrosa-v0.21.1-x86_64-unknown-linux-musl.tar.gz"
      sha256 "f3e3ed4f987e56b148a3eea16803e62f085c85762aab2b71f17ad6b6aab373f7"
    end
  end

  def install
    bin.install "ferrosa"
    bin.install "ferrosa-ctl"
    (etc/"ferrosa").install "config/ferrosa.example.toml" if File.exist?("config/ferrosa.example.toml")
  end

  def caveats
    <<~EOS
      Ferrosa installed. A default config example is at:
        #{etc}/ferrosa/ferrosa.example.toml

      Start it manually:
        FERROSA_CONFIG="#{etc}/ferrosa/ferrosa.example.toml" ferrosa

      Brew tracks the stable channel. For nightlies use the curl installer:
        curl -fsSL https://ferrosadb.com/install.sh | bash -s -- --channel nightly
    EOS
  end

  test do
    # The main `ferrosa` binary boots the server on any args; `ferrosa-ctl`
    # is the CLI with a clean --version.
    assert_match version.to_s, shell_output("#{bin}/ferrosa-ctl --version")
  end
end
