# typed: false
# frozen_string_literal: true

# Generated by scripts/sync.sh — do not edit by hand.
class Forge < Formula
  desc "Developer tooling CLI (frg) and MCP server for the Ferrosa suite"
  homepage "https://github.com/ferrosadb/forge"
  version "2026.09.19.0445"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ferrosadb/forge/releases/download/v2026.09.19.0445/frg-macos-aarch64.tar.gz"
      sha256 "c43d5400afa2d3948e47baee591002eb73332dfced42e0154328993330559171"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ferrosadb/forge/releases/download/v2026.09.19.0445/frg-linux-x86_64.tar.gz"
      sha256 "76c0322328a1c5475c1e2811d191e205bbc23ffa4ff28325964665d3c3a4c9f9"
    end
  end

  def install
    bin.install "frg"
  end

  def caveats
    <<~EOS
      The forge CLI is installed as `frg`. Run `frg --help` for commands.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/frg --version")
  end
end
