# typed: false
# frozen_string_literal: true

# Generated by scripts/sync.sh — do not edit by hand.
class Forge < Formula
  desc "Developer tooling CLI (frg) and MCP server for the Ferrosa suite"
  homepage "https://github.com/ferrosadb/forge"
  version "2026.09.28.0535"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ferrosadb/forge/releases/download/v2026.09.28.0535/frg-macos-aarch64.tar.gz"
      sha256 "f46163a37668b7485eea0e2f945ce0ec45268ca84f08a2403e754ed413f153ef"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ferrosadb/forge/releases/download/v2026.09.28.0535/frg-linux-x86_64.tar.gz"
      sha256 "e61c72c2a7ba9eef73de3942a0b9748fc50d160cbc3e1aa27a361eeb05ac652a"
    end
  end

  def install
    bin.install "frg"
  end

  def caveats
    <<~EOS
      The forge CLI is installed as `frg`. Run `frg --help` for commands.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/frg --version")
  end
end
