#!/usr/bin/env bash
# Regenerate the ferrosa Homebrew formulae from the latest STABLE GitHub
# releases. Single source of truth: the committed Formula/*.rb files are always
# the output of this script, so they cannot drift from the real release assets.
#
# Brew tracks the *stable* channel only (the maintainer-promoted "latest"
# release), matching the curl installers at ferrosadb.com.
#
# Idempotent: only rewrites a formula when its resolved version/sha changes.
# Fails loud: a missing release, missing asset, or missing checksum aborts with
# a non-zero exit rather than emitting a half-built formula.
set -euo pipefail
cd "$(dirname "$0")/.."

die() { printf 'error: %s\n' "$*" >&2; exit 1; }

latest_stable() { # repo -> tag (e.g. v0.16.0)
  local tag
  tag=$(curl -fsSL "https://api.github.com/repos/$1/releases/latest" \
          | sed -n 's/.*"tag_name": *"\([^"]*\)".*/\1/p' | head -1)
  [ -n "$tag" ] || die "no stable release for $1"
  printf '%s' "$tag"
}

sha_for() { # repo tag asset -> sha256
  local sums sha
  sums=$(curl -fsSL "https://github.com/$1/releases/download/$2/SHA256SUMS") \
    || die "cannot fetch SHA256SUMS for $1 $2"
  sha=$(printf '%s\n' "$sums" | awk -v a="$3" '$2==a{print $1}')
  [ -n "$sha" ] || die "no checksum for asset $3 in $1 $2"
  printf '%s' "$sha"
}

write_ferrosa() {
  local repo="ferrosadb/ferrosa" tag ver base
  tag=$(latest_stable "$repo"); ver="${tag#v}"
  base="https://github.com/${repo}/releases/download/${tag}"
  local mac_arm lin_arm lin_x86
  mac_arm=$(sha_for "$repo" "$tag" "ferrosa-${tag}-aarch64-apple-darwin.tar.gz")
  lin_arm=$(sha_for "$repo" "$tag" "ferrosa-${tag}-aarch64-unknown-linux-musl.tar.gz")
  lin_x86=$(sha_for "$repo" "$tag" "ferrosa-${tag}-x86_64-unknown-linux-musl.tar.gz")
  cat > Formula/ferrosa.rb <<RB
# typed: false
# frozen_string_literal: true

# Generated by scripts/sync.sh — do not edit by hand.
class Ferrosa < Formula
  desc "Cassandra-compatible database engine with S3-backed storage"
  homepage "https://ferrosadb.com"
  version "${ver}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "${base}/ferrosa-${tag}-aarch64-apple-darwin.tar.gz"
      sha256 "${mac_arm}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/ferrosa-${tag}-aarch64-unknown-linux-musl.tar.gz"
      sha256 "${lin_arm}"
    end
    on_intel do
      url "${base}/ferrosa-${tag}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "${lin_x86}"
    end
  end

  def install
    bin.install "ferrosa"
    bin.install "ferrosa-ctl"
    (etc/"ferrosa").install "config/ferrosa.example.toml" if File.exist?("config/ferrosa.example.toml")
  end

  def caveats
    <<~EOS
      Ferrosa installed. A default config example is at:
        #{etc}/ferrosa/ferrosa.example.toml

      Start it manually:
        FERROSA_CONFIG="#{etc}/ferrosa/ferrosa.example.toml" ferrosa

      Brew tracks the stable channel. For nightlies use the curl installer:
        curl -fsSL https://ferrosadb.com/install.sh | bash -s -- --channel nightly
    EOS
  end

  test do
    assert_match "ferrosa", shell_output("#{bin}/ferrosa --version")
  end
end
RB
  echo "wrote Formula/ferrosa.rb (${tag})"
}

write_ferrosa_memory() {
  local repo="ferrosadb/ferrosa-memory" tag ver base
  tag=$(latest_stable "$repo"); ver="${tag#v}"
  base="https://github.com/${repo}/releases/download/${tag}"
  local mac_arm lin_arm lin_x86
  mac_arm=$(sha_for "$repo" "$tag" "ferrosa-memory-${tag}-aarch64-apple-darwin.tar.gz")
  lin_arm=$(sha_for "$repo" "$tag" "ferrosa-memory-${tag}-aarch64-unknown-linux-musl.tar.gz")
  lin_x86=$(sha_for "$repo" "$tag" "ferrosa-memory-${tag}-x86_64-unknown-linux-musl.tar.gz")
  cat > Formula/ferrosa-memory.rb <<RB
# typed: false
# frozen_string_literal: true

# Generated by scripts/sync.sh — do not edit by hand.
class FerrosaMemory < Formula
  desc "Memory/knowledge-graph MCP server backed by Ferrosa"
  homepage "https://ferrosadb.com"
  version "${ver}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "${base}/ferrosa-memory-${tag}-aarch64-apple-darwin.tar.gz"
      sha256 "${mac_arm}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/ferrosa-memory-${tag}-aarch64-unknown-linux-musl.tar.gz"
      sha256 "${lin_arm}"
    end
    on_intel do
      url "${base}/ferrosa-memory-${tag}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "${lin_x86}"
    end
  end

  def install
    bin.install "ferrosa-memory-mcp"
    (etc/"ferrosa").install "config/ferrosa-memory.example.toml" if File.exist?("config/ferrosa-memory.example.toml")
  end

  def caveats
    <<~EOS
      ferrosa-memory-mcp installed. It connects to a running Ferrosa instance
      at localhost:9042 — install Ferrosa first:
        brew install ferrosadb/tap/ferrosa

      Register with Claude Code by adding to your MCP config:
        {
          "mcpServers": {
            "ferrosa-memory": {
              "command": "#{bin}/ferrosa-memory-mcp",
              "env": { "FERROSA_MEMORY_CONFIG": "#{etc}/ferrosa/ferrosa-memory.example.toml" }
            }
          }
        }
    EOS
  end

  test do
    assert_match "ferrosa-memory", shell_output("#{bin}/ferrosa-memory-mcp --version")
  end
end
RB
  echo "wrote Formula/ferrosa-memory.rb (${tag})"
}

write_ferrosa
write_ferrosa_memory
echo "done."
